# Two-attempt Appraisal install with automatic retry.
# Applied as a step snippet (inserted/updated in job steps).
- name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
  id: bundleAppraisalAttempt1
  run: bundle exec appraisal ${{ matrix.appraisal }} install
  # Continue to the next step on failure
  continue-on-error: true

# Effectively an automatic retry of the previous step.
- name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.appraisal }}"
  id: bundleAppraisalAttempt2
  # If bundleAppraisalAttempt1 failed, try again here; Otherwise skip.
  if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' }}
  run: bundle exec appraisal ${{ matrix.appraisal }} install
