# Coverage upload and PR comment steps.
# Applied as step snippets (appended to coverage job steps).

# Do SaaS coverage uploads first
- name: Upload coverage to Coveralls
  if: ${{ !env.ACT }}
  uses: coverallsapp/github-action@0a51d2e0b5417d06e4ecceb534aec87defc53926 # main
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
  continue-on-error: ${{ matrix.experimental != 'false' }}

- name: Upload coverage to QLTY
  if: ${{ !env.ACT }}
  uses: qltysh/qlty-action/coverage@a19242102d17e497f437d7466aa01b528537e899 # v2.2.0
  with:
    token: ${{secrets.QLTY_COVERAGE_TOKEN}}
    files: coverage/.resultset.json
  continue-on-error: ${{ matrix.experimental != 'false' }}

# Build will fail here if coverage upload fails
#   which will hopefully be noticed for the lack of code coverage comments
- name: Upload coverage to CodeCov
  if: ${{ !env.ACT }}
  uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
  with:
    use_oidc: true
    fail_ci_if_error: false # optional (default = false)
    files: coverage/lcov.info,coverage/coverage.xml
    verbose: true # optional (default = false)

# Then PR comments
- name: Code Coverage Summary Report
  if: ${{ !env.ACT && github.event_name == 'pull_request' }}
  uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
  with:
    filename: ./coverage/coverage.xml
    badge: true
    fail_below_min: true
    format: markdown
    hide_branch_rate: false
    hide_complexity: true
    indicators: true
    output: both
    thresholds: '100 100'
  continue-on-error: ${{ matrix.experimental != 'false' }}

- name: Add Coverage PR Comment
  uses: marocchino/sticky-pull-request-comment@d4d6b0936434b21bc8345ad45a440c5f7d2c40ff # v3.0.3
  if: ${{ !env.ACT && github.event_name == 'pull_request' }}
  with:
    recreate: true
    path: code-coverage-results.md
  continue-on-error: ${{ matrix.experimental != 'false' }}
