# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module Kettle
  module Soup
    module Cover
      CI: String
      COMMAND_NAME: String
      CONSTANTS: Array[String]
      COVERAGE_DIR: String
      DEBUG: bool
      DO_COV: bool
      ENV_GET: Proc
      FALSE: String
      FILTER_DIRS: Array[Regexp]
      FORMATTERS: Array[Hash[Symbol, Hash[Symbol, String | Symbol]]]
      FORMATTER_PLUGINS: Hash[Symbol, Hash[Symbol, String | Symbol]]
      IS_CI: bool
      MERGE_TIMEOUT: Integer?
      MIN_COVERAGE_BRANCH: Integer
      MIN_COVERAGE_HARD: bool
      MIN_COVERAGE_LINE: Integer
      MULTI_FORMATTERS: bool
      MULTI_FORMATTERS_DEFAULT: String
      PREFIX: String
      TRUE: String
      USE_MERGING: bool?
      VERBOSE: bool
      VERSION: String

      def delete_const: -> void

      def install_tasks: -> void

      def load_filters: -> void

      def load_formatters: -> void

      def reset_const: -> void
    end
  end
end
