name: Test Coverage

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  K_SOUP_COV_DEBUG: true
  K_SOUP_COV_DO: true
  K_SOUP_COV_HARD: true
  K_SOUP_COV_MIN_BRANCH: 46
  K_SOUP_COV_MIN_LINE: 93
  K_SOUP_COV_VERBOSE: true
  K_SOUP_COV_FORMATTERS: "xml,rcov,lcov,tty"
  K_SOUP_COV_MULTI_FORMATTERS: true
  K_SOUP_COV_COMMAND_NAME: "Test Coverage"

on:
  push:
    branches:
      - "main"
      - "*-stable"
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - "*"
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  coverage:
    name: Code Coverage on ${{ matrix.ruby }}@current
    if: ${{ !contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE - set at job level, so applies to all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Coverage
          - ruby: "ruby"
            appraisal: "coverage"
            exec_cmd: "rake test"
            gemfile: "coverage"
            rubygems: latest
            bundler: latest
            experimental: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: true

      - name: Run ${{ matrix.exec_cmd }} on ${{ matrix.ruby }}
        run: |
          bundle exec ${{ matrix.exec_cmd }}

      # Do SaaS coverage uploads first
      - name: Upload coverage to Coveralls
        if: ${{ !env.ACT }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: ${{ matrix.experimental != 'false' }}

      - name: Upload coverage to QLTY
        if: ${{ !env.ACT }}
        uses: qltysh/qlty-action/coverage@main
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage/.resultset.json
        continue-on-error: ${{ matrix.experimental != 'false' }}

      # Build will fail here if coverage upload fails
      #   which will hopefully be noticed for the lack of code coverage comments
      - name: Upload coverage to CodeCov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      # Then PR comments
      - name: Code Coverage Summary Report
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '93 46'
        continue-on-error: ${{ matrix.experimental != 'false' }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
        continue-on-error: ${{ matrix.experimental != 'false' }}
